Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,3 +1,5 @@
+#Template to be used by dotnet core applications
+
 image: alpine:latest
 
 variables:
@@ -28,6 +30,13 @@ stages:
 
 include:
   - template: Auto-DevOps.gitlab-ci.yml
+
+before_script:
+  - if [ $SLUG ]; then
+       export CI_PROJECT_PATH_SLUG='$SLUG' && export SONAR_K='$SLUG'
+    else
+       echo "$$SLUG variable is required (its like project name, lowercase and using dot as space character)" && exit 1
+    fi
 
 postman_scenarios:
   stage: validation
